### ISSUE TITLE
Dude! This rocks!

### ISSUE THREAD

**Issue by jphastings** [chendo/dmap-ng#1]
Glad my gem helped out - even if you did rewrite from scratch (could you tell I was learning ruby as I went? :P)

Your DSL is one heck of a lot sweeter than mine ever was, hence I'll be using dmap-ng to try and convince sinatra to serve video from Plexapp to the new AppleTV. (If you ever want to write a DAAP server with sinatra, take note of [this issue](https://github.com/sinatra/sinatra/issues#issue/113) I found).

(And yeah, this isn't really an issue, just wanted my excitement at a 'real' dmap project being out there on the public record :P)

**Comment by chendo** [comment]
Yes, I could :p

I shelved the project I wrote this gem for so it's not maintained very well, but if you submit any issues, I'll definitely look in to it and fix it if I can :)

**Comment by jphastings** [comment]
Thanks! If I can ever remember how to do it I'll remove my dmap from rubygems, as it'll probably confuse someone somewhere down the line!
