### ISSUE TITLE
StringIO not required in dmap executable

### ISSUE THREAD

**Issue by jphastings** [chendo/dmap-ng#2]
Real issue this time, I'm getting errors (ruby 1.9.1) where StringIO isn't available:

```
dmap-ng-0.2.6/lib/dmap/parser.rb:4:in `parse': uninitialized constant DMAP::Parser::StringIO (NameError)
from dmap-ng-0.2.6/lib/dmap.rb:23:in `parse'
from dmap-ng-0.2.6/bin/dmap:21:in `<top (required)>'
from /usr/local/bin/dmap:19:in `load'
from /usr/local/bin/dmap:19:in `<main>'
```

**Comment by chendo** [comment]
Out of curiosity, is it fixed if you add require "stringio" to the top of that file? My dev environment is majorly boned right now so I can't even run rake spec on it :(

**Comment by jphastings** [comment]
Yeah it does work (as far as I can tell!)

Do you use RVM? It makes creating a new ruby dev environment pretty simple.
